<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="55239" started-at="2019-04-07T15:24:01Z" finished-at="2019-04-07T15:24:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="55239" started-at="2019-04-07T15:24:01Z" finished-at="2019-04-07T15:24:56Z">
      <class name="rediffTests.buyOrSellStockTest">
        <test-method status="PASS" signature="buySellStock()[pri:0, instance:rediffTests.buyOrSellStockTest@1d384ee]" name="buySellStock" duration-ms="54274" started-at="2019-04-07T20:54:01Z" finished-at="2019-04-07T20:54:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buySellStock -->
        <test-method status="FAIL" signature="checkTransactionHistory()[pri:0, instance:rediffTests.buyOrSellStockTest@1d384ee]" name="checkTransactionHistory" duration-ms="951" started-at="2019-04-07T20:54:55Z" finished-at="2019-04-07T20:54:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [503.92015968063873] but found [503.92]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [503.92015968063873] but found [503.92]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at rediffTests.buyOrSellStockTest.checkTransactionHistory(buyOrSellStockTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTransactionHistory -->
      </class> <!-- rediffTests.buyOrSellStockTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
